config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :customers
  resources :comments, only: [:create, :destroy]
  root 'customers#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, presence: true
  validates :customer_id, presence: true
  belongs_to :customer
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :customers
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  def full_name(sama)
    full_name = family_name + given_name + sama
    return full_name
  end
  belongs_to :company
  has_many :comments
  validates :family_name, presence: true, length: { maximum: 20 }
  validates :given_name, presence: true, length: { maximum: 20 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
    presence: true, format: { with: VALID_EMAIL_REGEX }
    validates :company_id, presence: true
    # presence: true 値が空でないか？
end

app/models/migration.rb
class Migration < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :family_name
    devise_parameter_sanitizer.for(:sign_up) << :given_name
    devise_parameter_sanitizer.for(:sign_up) << :image_url
    devise_parameter_sanitizer.for(:account_update) << :family_name
    devise_parameter_sanitizer.for(:account_update) << :given_name
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.save
    redirect_to customer_url(@comment.customer_id)
  end

  def destroy
    @comment = Comment.find(params[:id])
    customer_id = @comment.customer_id
    @comment.destroy
    redirect_to customer_url(customer_id)
  end

  def comment_params
    params.require(:comment).permit(:body, :customer_id)
  end


end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy ]
  # before_action :authenticate_user!
  before_action :authenticate_user!
  def index
    # @customers = customer.all
    # @customers = Customer.page(params[:page])
    @q = Customer.ransack(params[:q])
    # 定型文
    @customers = @q.result.page(params[:page])
    # resultメソッドを使う。page(params[:page])はkaminariの記法
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
    redirect_to @customer
  else
    render :new
  end
end

  def edit
    # @customer = Customer.find(params[:id])
  end

  def update
    # @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to @customer
    else
      render :edit
    end
  end

  def show
    # @customer = Customer.find(params[:id])
    @comment = Comment.new
    @comments = @customer.comments
  end

  def destroy
    # @customer = Customer.find(params[:id])
    @customer.destroy
    redirect_to customers_url
  end

  private
  def customer_params
    params.require(:customer).permit(
      :family_name,
      :given_name,
      :email,
      :company_id
      )
  end
  def set_customer
    @customer = Customer.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div class="alert alert-danger">
      <p><b><%= @customer.errors.count %>件のエラーがあります</b></p>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :family_name %><br>
    <%= f.text_field :family_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :given_name %><br>
    <%= f.text_field :given_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email, class: "form-control" %>
  </div>
    <div class="form-group">
    <%= f.label :company_id %><br>
    <%= f.collection_select(:company_id, Company.all, :id, :name, class: "form-control") %>
  </div>
  <%= f.submit %>
<% end %>

app/views/customers/edit.html.erb
<div class="row">
 <div class="col-lg-12">
   <h1>顧客情報編集</h1>
   <%= render 'form' %>
   <%= link_to '削除する', @customer, method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-danger" %>
   <button type="button" class="btn btn-default btn-sm" data-toggle="modal" data-target="#delete-customer">顧客情報を削除する</button>
 </div>
</div>

<!-- 下記のモーダルは通常は隠れているので、どこに書いてもＯＫ -->
<div class="modal fade" id="delete-customer">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">顧客情報の削除</h4>
      </div>
      <div class="modal-body">
        <p><%= @customer.family_name %>さんを削除しますか？</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">キャンセル</button>
        <%= link_to '削除する', @customer, method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/customers/index.html.erb
    <h1>顧客情報一覧</h1>
    <p>お客様情報が表示されます。</p>

    <%= search_form_for @q do |f| %>
      <div class="row">
        <div class="col-sm-3 col-xs-12">
          <div class="form-group">
            <%= f.label :family_name_cont, '姓' %>
            <%= f.search_field :family_name_cont, class: "form-control input-sm" %>
          </div>
        </div>
        <div class="col-sm-3 col-xs-12">
          <div class="form-group">
            <%= f.label :given_name_cont, '名' %>
            <%= f.search_field :given_name_cont, class: "form-control input-sm" %>
          </div>
        </div>
        <div class="col-sm-3 col-xs-12">
          <div class="form-group">
            <%= f.label :email_cont, '電子メール' %>
            <%= f.search_field :email_cont, class: "form-control input-sm" %>
          </div>
        </div>
        <div class="col-sm-3 col-xs-12">
          <div class="form-group">
            <%= f.label :company_name_cont, '会社名' %>
            <%= f.search_field :company_name_cont, class: "form-control input-sm" %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12 text-center">
          <%= f.submit "検索", class: "btn btn-default" %>
        </div>
      </div>
    <% end -%>

    <hr />



<table class="table table-srriped">
 <thead>
  <th><%= sort_link(@q, :family_name, "姓") %></th>
  <th><%= sort_link(@q, :given_name, "名") %></th>
  <th><%= sort_link(@q, :email, "電子メール") %></th>
  <th><%= sort_link(@q, :company_name, "会社名") %></th>
  <th>コメント数</th>
  <th>リンク</th>
 </thead>
 <tbody>
   <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.family_name %></td>
      <td><%= customer.given_name %></td>
      <td><%= customer.email %></td>
      <td><%= customer.company.name %></td>
      <td><%= customer.comments.count %></td>
      <td><%= link_to '詳細', customer, class: "btn btn-default btn-xs" %></td>
    </tr>
    <% end %>
 </tbody>
 </table>
 <%= paginate @customers %>

app/views/customers/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>顧客新規登録</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/customers/show.html.erb
<div class="row">
 <div class="col-lg-12">
  <h1>顧客詳細</h1>
  <dl>
    <dt>お名前</dt>
    <dd><%= @customer.family_name %> <%= @customer.given_name %></dd>
    <dd><%= @customer.full_name("様") %></dd>
    <dt>電子メール</dt>
    <dd><%= @customer.email %></dd>
    <dt>会社名</dt>
    <dd><%= @customer.company.name %></dd>
  </dl>
 </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <h2>対応履歴</h2>
    <% @comments.each do |comment| %>
    <div class="media">
  <div class="media-body">
    <p><%= simple_format(comment.body) %></p>
    <p class="text-muted">
      投稿日時:<%= comment.created_at.strftime('%Y/%m/%d/ %H:%M') %>
      <%= link_to "削除する", comment_path(comment), method: :delete %>
      </p>
  </div>
      </div>
    <% end %>
  </div>
</div>

<hr />

<div class="row">
  <div class="col-lg-12">
    <%= form_for(@comment, url: { controller: :comments, action: :create }) do |f| %>
      <div class="form-group">
        <%= f.label :body , '対応内容' %><br>
        <%= f.text_area :body, class: "form-control" %>
      </div>
      <%= f.hidden_field :customer_id, value: @customer.id %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-menu">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/customers">顧客管理システム</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse-menu">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "設定変更", edit_user_registration_path %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "新規登録", new_user_registration_path %></li>
          <li><%= link_to "ログイン", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SprtaCrm1223</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</head>
<body>
<%= render partial: 'layouts/header' %>

<div class="container">
  <% if notice.present? %>
    <div class="alert alert-dismissable alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <p><%= notice %></p>
    </div>
  <% end %>

  <% if alert.present? %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <p><%= alert %></p>
    </div>
  <% end %>

  <%= yield %>
</div>
</body>
</html>